/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Phil_XG (https://sketchfab.com/phil_xg)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bastion-ganymede-overwatch-b25da6e53d304c00a6bda81d26114ac5
title: Bastion & Ganymede - Overwatch
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/modelDraco.gltf')
  return (

    <group {...props} dispose={null} >
      <group rotation={[-Math.PI / 2 , 0, 3.4]} scale={0.37}   >
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material2} />
      </group>
    </group>

  )
}

useGLTF.preload('/modelDraco.gltf')

export default Model
